// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Grs.BioRestock.Infrastructure.Contexts;
using Grs.BioRestock.Infrastructure.Extensions;
using Grs.BioRestock.Domain.Entities;

namespace Grs.BioRestock.Infrastructure.Contexts
{
    public partial class UniContext
    {

        public UniContext(DbContextOptions<UniContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BonDeRetour> BonDeRetours { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<DemandeSignature> DemandeSignatures { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnIdentityModelCreating(modelBuilder);

            modelBuilder.Entity<Domain.Entities.BonDeRetour>(entity =>
            {
                entity.ToTable("BonDeRetour");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Domain.Entities.Customer>(entity =>
            {
                entity.ToTable("Customer");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Domain.Entities.Article>(entity =>
            {
                entity.ToTable("Article");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<Domain.Entities.DemandeSignature>(entity =>
            {
                entity.ToTable("DemandeSignature");
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

        }

        //protected override void OnModelCreating(ModelBuilder modelBuilder)
        //{
        //    OnIdentityModelCreating(modelBuilder);

        //    OnModelCreatingGenerated(modelBuilder);


        //   // OnModelCreatingPartial(modelBuilder);
        //}

        //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}